name: reaxios
description: A new Flutter project.
publish_to: "none"
version: 0.7.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  connectivity_plus: ^7.0.0
  fl_chart: ^1.1.1
  flutter_linkify: ^6.0.0
  flutter_markdown: ^0.7.1
  flutter_material_color_picker: ^1.1.0+2
  flutter_mobx: ^2.0.4
  flutter_settings_screens: ^0.3.2-null-safety
  flutter_spinkit: ^5.1.0
  html: ^0.15.0
  intl: ^0.20.2
  json_annotation: ^4.4.0
  mobx: ^2.0.6+1
  package_info_plus: ^9.0.0
  provider: ^6.0.2
  # settings_ui: ^2.0.2
  shared_preferences: ^2.0.13
  sticky_headers: ^0.3.0+2
  styled_widget: ^0.4.0+3
  table_calendar: ^3.0.3
  url_launcher: ^6.0.18

  # For the push notifications on Android
  android_alarm_manager_plus: ^5.0.0
  flutter_local_notifications: ^20.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animations: ^2.0.2
  google_fonts: ^8.0.2
  just_bottom_sheet: ^1.2.0
  copy_with_extension: ^12.1.0
  share_plus: ^12.0.1
  file_picker: ^10.3.10
  duration: ^4.0.3
  flutter_week_view: ^1.2.1+1
  flutter_typeahead: ^5.2.0
  upgrader: ^12.5.0
  universal_io: ^2.0.4
  badges: ^3.1.2
  bloc: ^9.2.0
  equatable: ^2.0.3
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  hydrated_bloc: ^10.1.1
  path_provider: ^2.0.9
  flutter_sticky_header: ^0.8.0
  dynamic_color: ^1.6.2
  screenshot: ^3.0.0
  device_info_plus: ^12.3.0
  http: ^1.6.0
  logger:
    path: packages/logger
  axios_api:
    path: packages/axios_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    # l10n
    - assets/locales/en.json
    - assets/locales/it.json